# Generated by Django 3.2.4 on 2023-08-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20230808_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/blog/default.jpg', upload_to='blog/'),
        ),
    ]
